---
title: "Preparing Climate Data for Use With LANDIS-II"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Preparing Climate Data for Use With LANDIS-II}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteDepends{bcdata,scfmutils,SpaDES.tools,terra}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
## package list should match %\VignetteDepends above!
VignetteDepends <- c("bcdata", "scfmutils", "SpaDES.tools", "terra")
all_pkgs_avail <- vapply(VignetteDepends, function(pkg) {
  require(pkg, character.only = TRUE, quietly = TRUE)
}, logical(1)) |>
  all()

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = all_pkgs_avail
)
```

```{r setup}
library(landisutils)
```

## Define a 'study area' or 'area of interest'

```{r, study-area}
studyAreaBC <- terra::vect(cbind(-122.14, 52.14), crs = "epsg:4326") |>
    terra::project(paste("+proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95",
                         "+x_0=0 +y_0=0 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0")) |>
    SpaDES.tools::randomStudyArea(seed = 60, size = 1e10)

## we can safely ignore the following warnings:
## "attribute variables are assumed to be spatially constant throughout all geometries"
ecoregionPolys <- suppressWarnings({
  scfmutils::prepInputsFireRegimePolys(studyArea = studyAreaBC, type = "BECNDT")
})

plot(ecoregionPolys["PolyID"])
```

## Historical weather data

```{r setup-climate}
clim_years <- 2018:2019 ## availability is 1980 to last year

clim_data_path <- file.path(tempdir(), "climate_data")
dir.create(clim_data_path)
```

### BioSIM

```{r get-biosim-data, eval = FALSE}
climvars <- c(
  ## BioSIM::getModelHelp("ClimaticEx_Daily")
  "Prcp", "SRad", "RelH", "Tair", "Tmax", "Tmin", "WndD", "WndS",
  
  ## BioSIM::getModelHelp("Potential_Evapotranspiration_Daily")
  ## BioSIM::getModelHelp("Potential_Evapotranspiration_Ex_Daily")
  "PET"
)

## TODO: use Prcp / 10 (must be in cm);
## TODO: convert WndS from km/h to m/s;
## TODO: verify wind direction is the FROM Direction;

BioSIM::generateWeather(
  modelNames = c("ClimaticEx_Daily", "Potential_Evapotranspiration_Daily"),
  fromYr = head(clim_years, 1),
  toYr = tail(clim_years, 1),
  id = ,      ## TODO: e.g., 1:length(longDeg)
  latDeg = ,  ## TODO: extract points from gridded polygon
  longDeg = , ## TODO: extract points from gridded polygon
  elevM = rep(NA, length(longDeg)),
  rep = 1,
  repModel = 1,
  rcp = "RCP45",      ## shouldn't matter for historical, but FRV to use SSPs not RCPs;
  climModel = "RCM4", ## shouldn't matter for historical, but FRV to use SSPs not RCPs;
  additionalParms = NULL
)
## TODO: gridded values need to be summarized by ecolocation; i.e., `zonal`
```

### Daily Climate Data (Daymet)

```{r, get-daymet-data}
climvars <- c("prcp", "tmax", "tmin")

daily_weather <- purrr::map(
  .x = climvars,
  .f = prep_daily_weather,
  studyArea = ecoregionPolys,
  id = "PolyID",
  start = glue::glue("{head(clim_years, 1)}-01-01"),
  end = glue::glue("{tail(clim_years, 1)}-12-31")
) |>
  purrr::list_rbind()

head(daily_weather)

clim_file <- file.path(clim_data_path, "climate-data-daily.csv")
writeClimateData(daily_weather, clim_file)
```

### Monthly Climate Data (TerraClim)

As above, we can get monthly data using the following recipe:

```{r, get-terraclim-data}
climvars <- c("ppt", "tmax", "tmin")

monthly_weather <- purrr::map(
  .x = climvars,
  .f = prep_monthly_weather,
  studyArea = ecoregionPolys,
  id = "PolyID",
  start = glue::glue("{head(clim_years, 1)}-01-01"),
  end = glue::glue("{tail(clim_years, 1)}-12-31")
) |>
  purrr::list_rbind() |>
  dplyr::filter(Year <= tail(clim_years, 1)) ## match end year

head(monthly_weather)

clim_file <- file.path(clim_data_path, "climate-data-monthly.csv")
writeClimateData(monthly_weather, clim_file)
```

We can also use this recipe to get monthly AET data to prepare the `EcoregionParameters` table:

```{r, get-terraclim-aet}
aet_df <- purrr::map(
  .x = "aet",
  .f = prep_monthly_weather,
  studyArea = ecoregionPolys,
  id = "PolyID",
  start = glue::glue("{head(clim_years, 1)}-01-01"),
  end = glue::glue("{tail(clim_years, 1)}-12-31")
) |>
  purrr::list_rbind() |>
  dplyr::filter(Year <= tail(clim_years, 1)) ## match end year

head(aet_df)

erp_df <- prepEcoregionParameters(aet_df)

head(erp_df)
```

## Climate projections

See <https://mikejohnson51.github.io/climateR/articles/intro.html#climate-projections>

```{r, get-maca-data}
## TODO
```

<!-- cleanup -->

```{r cleanup, include = FALSE}
unlink(clim_data_path, recursive = TRUE)
```
