---
title: "Preparing Forest Carbon Succession (ForCS) Inputs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Preparing Forest Carbon Succession (ForCS) Inputs}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(landisutils)

tmp_pth <- withr::local_tempdir("example_ForCS_")
```

## Sample extension inputs

```{r forest-carbon-succession-inputs}
clim_df <- tibble::tribble(
  ~year , ~ecoregion , ~avg_temp ,
      0 , "eco1"     , 5         ,
      0 , "eco2"     , 2         ,
      5 , "eco1"     , 5.5       ,
      5 , "eco2"     , 2.5       ,
     10 , "eco1"     , 6         ,
     10 , "eco2"     , 3         ,
     20 , "eco1"     , 7         ,
     20 , "eco2"     , 5
)

disturb_fire_dom <- tibble::tribble(
  ~intensity , ~from_dom , ~to_air , ~to_dom , ~to_fps ,
           1 ,         1 , 0.5     , 0.0     , 0.0     ,
           1 ,         3 , 0.2     , 0.0     , 0.0     ,
           2 ,         1 , 0.5     , 0.0     , 0.0     ,
           2 ,         2 , 0.25    , 0.0     , 0.0     ,
           2 ,         3 , 0.35    , 0.0     , 0.0     ,
           2 ,         8 , 0.0     , 0.5     , 0.0     ,
           2 ,         9 , 0.0     , 1.0     , 0.0     ,
           3 ,         1 , 0.65    , 0.0     , 0.0     ,
           3 ,         2 , 0.35    , 0.0     , 0.0     ,
           3 ,         3 , 0.4     , 0.0     , 0.0     ,
           3 ,         8 , 0.0     , 0.75    , 0.0     ,
           3 ,         9 , 0.5     , 0.5     , 0.0     ,
           4 ,         1 , 1.0     , 0.0     , 0.0     ,
           4 ,         2 , 0.5     , 0.0     , 0.0     ,
           4 ,         3 , 0.4     , 0.0     , 0.0     ,
           4 ,         5 , 0.1     , 0.0     , 0.0     ,
           4 ,         8 , 0.0     , 1.0     , 0.0     ,
           4 ,         9 , 0.7     , 0.3     , 0.0     ,
           5 ,         1 , 1.0     , 0.0     , 0.0     ,
           5 ,         2 , 0.65    , 0.0     , 0.0     ,
           5 ,         3 , 0.45    , 0.0     , 0.0     ,
           5 ,         5 , 0.1     , 0.0     , 0.0     ,
           5 ,         8 , 0.1     , 0.9     , 0.0     ,
           5 ,         9 , 0.7     , 0.3     , 0.0
)

disturb_other_dom <- tibble::tribble(
  ~disturb_type , ~from_dom , ~to_air , ~to_dom , ~to_fps ,
  "Clearcut"    ,         1 , 0.0     , 0.0     , 0.0     ,
  "Clearcut"    ,         8 , 0.0     , 0.4     , 0.6     ,
  "wind"        ,         8 , 0.0     , 0.8     , 0.0     ,
  "wind"        ,         9 , 0.0     , 1.0     , 0.0
)

disturb_fire_biomass = tibble::tribble(
  ~intensity , ~from_biomass , ~to_air , ~to_fps , ~to_dom ,
           1 ,             1 , 0       ,       0 , 1       ,
           1 ,             2 , 0.5     ,       0 , 0.5     ,
           1 ,             3 , 0       ,       0 , 1       ,
           1 ,             5 , 0       ,       0 , 1       ,
           1 ,             6 , 0       ,       0 , 1       ,
           2 ,             1 , 0       ,       0 , 1       ,
           2 ,             2 , 0.7     ,       0 , 0.3     ,
           2 ,             3 , 0.1     ,       0 , 0.9     ,
           2 ,             5 , 0       ,       0 , 1       ,
           2 ,             6 , 0       ,       0 , 1       ,
           3 ,             1 , 0       ,       0 , 1       ,
           3 ,             2 , 0.75    ,       0 , 0.25    ,
           3 ,             3 , 0.1     ,       0 , 0.9     ,
           3 ,             5 , 0       ,       0 , 1       ,
           3 ,             6 , 0       ,       0 , 1       ,
           4 ,             1 , 0       ,       0 , 1       ,
           4 ,             2 , 1       ,       0 , 0       ,
           4 ,             3 , 0.2     ,       0 , 0.8     ,
           4 ,             5 , 0       ,       0 , 1       ,
           4 ,             6 , 0       ,       0 , 1       ,
           5 ,             1 , 0       ,       0 , 1       ,
           5 ,             2 , 1       ,       0 , 0       ,
           5 ,             3 , 0.3     ,       0 , 0.7     ,
           5 ,             5 , 0       ,       0 , 1       ,
           5 ,             6 , 0       ,       0 , 1
)

disturb_other_biomass = tibble::tribble(
  ~disturb_type , ~from_biomass , ~to_air , ~to_fps , ~to_dom ,
  "Clearcut"    ,             1 , 0       ,       1 , 0       ,
  "Clearcut"    ,             2 , 0       ,       0 , 1       ,
  "Clearcut"    ,             3 , 0       ,       0 , 1       ,
  "Clearcut"    ,             5 , 0       ,       0 , 1       ,
  "Clearcut"    ,             6 , 0       ,       0 , 1       ,
  "wind"        ,             1 , 0       ,       0 , 1       ,
  "wind"        ,             2 , 0       ,       0 , 1       ,
  "wind"        ,             3 , 0       ,       0 , 1       ,
  "wind"        ,             5 , 0       ,       0 , 1       ,
  "wind"        ,             6 , 0       ,       0 , 1       ,
  "bda"         ,             1 , 0       ,       0 , 1       ,
  "bda"         ,             2 , 0.3     ,       0 , 0.7     ,
  "bda"         ,             3 , 0.2     ,       0 , 0.8     ,
  "bda"         ,             5 , 0       ,       0 , 1       ,
  "bda"         ,             6 , 0       ,       0 , 1
)

snags <- tibble::tribble(
  ~species   , ~age_at_death , ~time_since_death , ~cause  ,
  "querelli" ,            53 ,                 5 , "other" ,
  "pinubank" ,            88 ,                12 , "bda"
)

output_tables <- data.frame(Biomass = 1, DOM_Pools = 1, Fluxes = 1, Summary = 1)

soil_spinup <- data.frame(Flag = 1, Tolerance = 1.0, MaxIter = 20)

avail_light_biomass <- data.frame(
  Class = 1L:5L,
  eco1 = c(30, 35, 55, 80, 100),
  eco2 = c(30, 35, 55, 80, 100)
)

light_est <- data.frame(
  class = 1L:5L,
  X0 = c(1.0, 0.5, 0.2, 0.1, 0.1),
  X1 = c(0.5, 1.0, 0.2, 0.1, 0.5),
  X2 = c(0.0, 0.5, 1.0, 0.2, 0.2),
  X3 = c(0.0, 0.0, 0.5, 1.0, 0.2),
  X4 = c(0.0, 0.0, 0.0, 0.5, 1.0),
  X5 = c(0.0, 0.0, 0.0, 0.5, 1.0)
)

species_params <- tibble::tribble(
  ~species   , ~leaf_long , ~mort_shp , ~min_age_merch , ~merch_shp_a , ~merch_shp_b , ~nonmerch_biomass_soil , ~growth_shp ,
  "pinubank" , 3.0        ,        10 ,             10 , 0.7546       , 0.983        , 0.25                   , 0.25        ,
  "querelli" , 1.0        ,        10 ,             30 , 0.7546       , 0.983        , 0.25                   , 0.25
)

dom_pools <- tibble::tribble(
  ~id , ~name                   , ~prop_to_atmosphere ,
    1 , "Very Fast Aboveground" , 0.815               ,
    2 , "Very Fast Belowground" , 0.83                ,
    3 , "Fast Aboveground"      , 0.83                ,
    4 , "Fast Belowground"      , 0.83                ,
    5 , "Medium"                , 0.83                ,
    6 , "Slow Aboveground"      , 1                   ,
    7 , "Slow Belowground"      , 1                   ,
    8 , "Stem Snag"             , 0.83                ,
    9 , "Other Snag"            , 0.83                ,
   10 , "Extra pool"            , 0.83
)

ecosppdom_params <- tibble::tribble(
  ~ecoregion , ~species   , ~dom_pool , ~decay_rate , ~amt_t0 , ~q10_ref_temp_10c ,
  "eco1"     , "pinubank" ,         1 , 0.355       ,   53.04 , 2.65              ,
  "eco1"     , "pinubank" ,         2 , 0.5         ,  295.4  , 2                 ,
  "eco1"     , "pinubank" ,         3 , 0.1435      , 1395.49 , 2                 ,
  "eco1"     , "pinubank" ,         4 , 0.0374      , 1360.62 , 2                 ,
  "eco1"     , "pinubank" ,         5 , 0.015       ,  863.88 , 2                 ,
  "eco1"     , "pinubank" ,         6 , 0.0033      , 1656.13 , 2.65              ,
  "eco1"     , "pinubank" ,         7 , 0.0187      , 8451.22 , 2                 ,
  "eco1"     , "pinubank" ,         8 , 0.07175     , 7466.54 , 2                 ,
  "eco1"     , "pinubank" ,         9 , 0.07        , 2036.14 , 2                 ,
  "eco1"     , "pinubank" ,        10 , 0           ,    0    , 2                 ,
  "eco2"     , "pinubank" ,         1 , 0.355       ,   53.04 , 2.65              ,
  "eco2"     , "pinubank" ,         2 , 0.5         ,  295.4  , 2                 ,
  "eco2"     , "pinubank" ,         3 , 0.1435      , 1395.49 , 2                 ,
  "eco2"     , "pinubank" ,         4 , 0.0374      , 1360.62 , 2                 ,
  "eco2"     , "pinubank" ,         5 , 0.015       ,  863.88 , 2                 ,
  "eco2"     , "pinubank" ,         6 , 0.0033      , 1656.13 , 2.65              ,
  "eco2"     , "pinubank" ,         7 , 0.0187      , 8451.22 , 2                 ,
  "eco2"     , "pinubank" ,         8 , 0.07175     , 7466.54 , 2                 ,
  "eco2"     , "pinubank" ,         9 , 0.07        , 2036.14 , 2                 ,
  "eco2"     , "pinubank" ,        10 , 0           ,    0    , 2                 ,
  "eco1"     , "querelli" ,         1 , 0.355       ,   53.04 , 2.65              ,
  "eco1"     , "querelli" ,         2 , 0.5         ,  295.4  , 2                 ,
  "eco1"     , "querelli" ,         3 , 0.1435      , 1395.49 , 2                 ,
  "eco1"     , "querelli" ,         4 , 0.0374      , 1360.62 , 2                 ,
  "eco1"     , "querelli" ,         5 , 0.015       ,  863.88 , 2                 ,
  "eco1"     , "querelli" ,         6 , 0.0033      , 1656.13 , 2.65              ,
  "eco1"     , "querelli" ,         7 , 0.0187      , 8451.22 , 2                 ,
  "eco1"     , "querelli" ,         8 , 0.07175     , 7466.54 , 2                 ,
  "eco1"     , "querelli" ,         9 , 0.07        , 2036.14 , 2                 ,
  "eco1"     , "querelli" ,        10 , 0           ,    0    , 2                 ,
  "eco2"     , "querelli" ,         1 , 0.355       ,   53.04 , 2.65              ,
  "eco2"     , "querelli" ,         2 , 0.5         ,  295.4  , 2                 ,
  "eco2"     , "querelli" ,         3 , 0.1435      , 1395.49 , 2                 ,
  "eco2"     , "querelli" ,         4 , 0.0374      , 1360.62 , 2                 ,
  "eco2"     , "querelli" ,         5 , 0.015       ,  863.88 , 2                 ,
  "eco2"     , "querelli" ,         6 , 0.0033      , 1656.13 , 2.65              ,
  "eco2"     , "querelli" ,         7 , 0.0187      , 8451.22 , 2                 ,
  "eco2"     , "querelli" ,         8 , 0.07175     , 7466.54 , 2                 ,
  "eco2"     , "querelli" ,         9 , 0.07        , 2036.14 , 2                 ,
  "eco2"     , "querelli" ,        10 , 0           ,    0    , 2
)

forcs_props <- data.frame(
  BiomassFine = 0.5,
  BiomassCoarse = 0.5,
  AnnualSlowAGtoSlowBG = 0.006,
  AnnualStemSnagToMedium = 0.032,
  AnnualBranchSnagToFastAG = 0.1
)

anpp_timeseries <- tibble::tribble(
  ~year , ~ecoregion , ~species   , ~anpp , ~anpp_std ,
      0 , "eco1"     , "pinubank" ,   648 ,         0 ,
      0 , "eco1"     , "querelli" ,  1415 ,         0 ,
      0 , "eco2"     , "pinubank" ,   648 ,         0 ,
      0 , "eco2"     , "querelli" ,  1415 ,         0
)

maxb_timeseries <- tibble::tribble(
  ~year , ~ecoregion , ~species   , ~maxb ,
      0 , "eco1"     , "pinubank" , 15000 ,
      0 , "eco1"     , "querelli" , 25000 ,
      0 , "eco2"     , "pinubank" , 15000 ,
      0 , "eco2"     , "querelli" , 25000
)

est_prob <- tibble::tribble(
  ~year , ~ecoregion , ~species   , ~probability ,
      0 , "eco1"     , "pinubank" , 0.1          ,
      0 , "eco1"     , "querelli" , 0.1          ,
      0 , "eco2"     , "pinubank" , 0.1          ,
      0 , "eco2"     , "querelli" , 0.1
)

root_dynamics <- tibble::tribble(
  ~ecoregion , ~species   , ~min_abio , ~root_abio , ~prop_fine_rt , ~fr_turnover , ~cr_turnover ,
  "eco1"     , "pinubank" ,         0 , 0.403      , 0.18          , 0.6          , 0.02         ,
  "eco1"     , "pinubank" ,      5000 , 0.292      , 0.1           , 0.6          , 0.02         ,
  "eco1"     , "querelli" ,         0 , 0.403      , 0.18          , 1            , 0.02         ,
  "eco2"     , "pinubank" ,         0 , 0.433      , 0.18          , 0.6          , 0.02         ,
  "eco2"     , "querelli" ,         0 , 0.403      , 0.18          , 1            , 0.02         ,
  "eco2"     , "querelli" ,      5000 , 0.292      , 0.1           , 0.6          , 0.02
)
```

## Extension configuration

```{r forest-carbon-succession-write}
## write the climate file
clim_file <- prepClimateFile(
  df = clim_df,
  path = tmp_pth,
  filename = "ForCS_climate.txt"
)

## write the disturbance matrix file
dm_file <- prepDisturbanceMatrixFile(
  DisturbFireTransferDOM = disturb_fire_dom,
  DisturbOtherTransferDOM = disturb_other_dom,
  DisturbFireTransferBiomass = disturb_fire_biomass,
  DisturbOtherTransferBiomass = disturb_other_biomass,
  path = tmp_pth,
  filename = "ForCS_DM.txt"
)

## write the snag file
snag_file <- prepSnagFile(
  snags,
  path = tmp_pth,
  filename = "ForCS_snags.txt"
)

## don't need working files, they just need to exist
init_comm_files <- c(
  file.path(tmp_pth, "initial-communities.txt"),
  file.path(tmp_pth, "initial-communities.gis")
)
purrr::walk2(.x = c("", ""), .y = init_comm_files, .f = writeLines)

## create the ForCS extension config object
ext_forcs <- ForCS$new(
  path = tmp_pth,
  Timestep = 1,
  SeedingAlgorithm = "WardSeedDispersal",
  ClimateFile = clim_file,
  InitialCommunitiesFiles = init_comm_files,
  DisturbanceMatrixFile = dm_file,
  SnagFile = snag_file,
  OutputTables = output_tables,
  SoilSpinupControls = soil_spinup,
  AvailableLightBiomass = avail_light_biomass,
  LightEstablishmentTable = light_est,
  SpeciesParameters = species_params,
  DOMPools = dom_pools,
  EcoSppDOMParameters = ecosppdom_params,
  ForCSProportions = forcs_props,
  ANPPTimeSeries = anpp_timeseries,
  MaxBiomassTimeSeries = maxb_timeseries,
  EstablishProbabilities = est_prob,
  RootDynamics = root_dynamics
)

## write the ForCS extension config file
ext_forcs$write()
```

## Verify configuration files

```{r forest-carbon-succession-config}
readLines(file.path(tmp_pth, ext_forcs$files[1]))
```

```{r forest-carbon-succession-climate}
readLines(file.path(tmp_pth, ext_forcs$files[2]))
```

*skip initial communities files*

```{r forest-carbon-succession-dist-mat}
readLines(file.path(tmp_pth, ext_forcs$files[5]))
```

```{r forest-carbon-succession-snags}
readLines(file.path(tmp_pth, ext_forcs$files[6]))
```

## Cleanup

```{r cleanup}
withr::deferred_run()
```
