testthat::test_that("landisutilsHeader() is byte-reproducible (version, no timestamp)", {
  h1 <- landisutils:::landisutilsHeader()
  h2 <- landisutils:::landisutilsHeader()
  ## two calls must be identical: a timestamp would break tar_landis()'s
  ## input-hash skip-check on every scenario re-write.
  testthat::expect_identical(h1, h2)
  ## the provenance line carries the package version but NOT a date/timestamp
  testthat::expect_match(h1[[1]], "generated by `landisutils` \\(v")
  testthat::expect_no_match(h1[[1]], "[0-9]{4}")
})
