testthat::test_that("landisutilsHeader() is byte-reproducible (version, no timestamp)", {
  h1 <- landisutils:::landisutilsHeader()
  h2 <- landisutils:::landisutilsHeader()
  ## two calls must be identical: a timestamp would break tar_landis()'s
  ## input-hash skip-check on every scenario re-write.
  testthat::expect_identical(h1, h2)
  ## the provenance line carries the package version but NOT a date/timestamp
  testthat::expect_match(h1[[1]], "generated by `landisutils` \\(v")
  testthat::expect_no_match(h1[[1]], "[0-9]{4}")
})

## .need() guards the Suggests-only capabilities (arrow, ggplot2/ggalluvial, cffdrs). Those packages
## are heavy -- arrow is 99 MB, cffdrs pulls 16 packages nothing else here needs -- so they are not
## Imports, and a caller who reaches one without it installed must get a message naming what to
## install rather than "there is no package called ..." from deep in the call stack.

testthat::test_that(".need() passes silently when the package is available", {
  testthat::expect_true(landisutils:::.need("stats", "Anything"))
  testthat::expect_silent(landisutils:::.need(c("stats", "utils"), "Anything"))
})

testthat::test_that(".need() names the missing package and how to install it", {
  testthat::expect_error(
    landisutils:::.need("notARealPackage", "Reading a parquet dataset"),
    "Reading a parquet dataset requires the 'notARealPackage' package",
    fixed = TRUE
  )
  testthat::expect_error(
    landisutils:::.need("notARealPackage", "Doing a thing"),
    'install.packages("notARealPackage")',
    fixed = TRUE
  )
})

testthat::test_that(".need() reports only the packages actually missing", {
  ## a caller naming several dependencies must not be told to install ones it already has
  err <- tryCatch(
    landisutils:::.need(c("stats", "notARealPackage", "alsoNotReal"), "Plotting"),
    error = function(e) conditionMessage(e)
  )
  testthat::expect_no_match(err, "stats")
  testthat::expect_match(err, "'notARealPackage' and 'alsoNotReal'", fixed = TRUE)
  testthat::expect_match(err, "packages.", fixed = TRUE)
})
