#' @keywords internal
.checkPath <- function(path) {
  path <- fs::path_norm(path)

  if (!fs::dir_exists(path)) {
    fs::dir_create(path)
  }

  path
}

#' @keywords internal
landisutilsVersion <- function() {
  packageVersion("landisutils")
}

#' @keywords internal
landisutilsHeader <- function() {
  c(
    glue::glue(">> generated by `landisutils` (v{landisutilsVersion()}) on {date()}"),
    glue::glue(">> do not edit by hand; manual changes to this file may be overwritten"),
    glue::glue("")
  )
}

#' @keywords internal
LandisData <- function(x) {
  c(
    landisutilsHeader(),
    glue::glue("LandisData  \"{x}\"")
  )
}
