#' @keywords internal
.checkPath <- function(path) {
  path <- fs::path_norm(path) |> fs::dir_create()

  return(path)
}

#' @keywords internal
landisutilsVersion <- function() {
  packageVersion("landisutils")
}

#' @keywords internal
landisutilsHeader <- function() {
  c(
    glue::glue(">> generated by `landisutils` (v{landisutilsVersion()}) on {date()}"),
    glue::glue(">> do not edit by hand; manual changes to this file may be overwritten"),
    glue::glue("")
  )
}

#' @keywords internal
LandisData <- function(x) {
  c(landisutilsHeader(), glue::glue("LandisData  \"{x}\""), glue::glue(""))
}

#' Specify an input parameter value for an extension
#'
#' @param type Character, specifying the parameter type (i.e., the LANDIS-II name for the input).
#'
#' @param value A single parameter value of integer, numeric, or character type.
#'
#' @template return_insert
#'
#' @keywords internal
insertValue <- function(type, value) {
  stopifnot(length(value) == 1)

  c(
    glue::glue("{type}    \"{value}\""),
    glue::glue("") ## add blank line after each item group
  )
}

#' Specify an input file for an extension
#'
#' Checks that a file exists before inserting the filepath.
#'
#' @param type Character, specifying the parameter type (i.e., the LANDIS-II name for the input).
#'
#' @template param_file
#'
#' @template return_insert
#'
#' @keywords internal
insertFile <- function(type, file) {
  stopifnot(!file.exists(file))

  insertValue(type, file)
}
