#' @keywords internal
.checkPath <- function(path) {
  path <- fs::path_norm(path) |> fs::dir_create()

  return(path)
}

#' @keywords internal
.relPath <- function(path, start = ".") {
  if (is.null(path) || is.na(path)) {
    path
  } else {
    fs::path_rel(path, start)
  }
}

#' @keywords internal
landisutilsVersion <- function() {
  packageVersion("landisutils")
}

#' @keywords internal
landisutilsHeader <- function() {
  c(
    glue::glue(">> generated by `landisutils` (v{landisutilsVersion()}) on {date()}"),
    glue::glue(">> do not edit by hand; manual changes to this file may be overwritten"),
    glue::glue("")
  )
}

#' @keywords internal
insertLandisData <- function(x) {
  c(landisutilsHeader(), glue::glue("LandisData  \"{x}\""), glue::glue(""))
}

#' Specify an input parameter value for an extension
#'
#' @param type Character, specifying the parameter type (i.e., the LANDIS-II name for the input).
#'
#' @param value A single parameter value of integer, numeric, or character type.
#'
#' @template return_insert
#'
#' @keywords internal
insertValue <- function(type, value) {
  stopifnot(length(value) == 1)

  c(
    glue::glue("{type}    \"{value}\""),
    glue::glue("") ## add blank line after each item group
  )
}

#' Specify an input file for an extension
#'
#' Checks that a file exists before inserting the filepath.
#'
#' @param type Character, specifying the parameter type (i.e., the LANDIS-II name for the input).
#'
#' @template param_file
#'
#' @template return_insert
#'
#' @keywords internal
insertFile <- function(type, file) {
  stopifnot(!file.exists(file))

  insertValue(type, file)
}

#' Convert logical to "yes" or "no"
#'
#' LANDIS-II input files use character strings "yes" and "no"
#' instead of logical TRUE or FALSE.
#'
#' @param x one of `TRUE`, `FALSE`, `Y`, `N`, `yes`, `no`.
#'
#' @return Character "yes" or "no".
#'
#' @export
yesno <- function(x) {
  stopifnot(
    "x must be one of TRUE, FALSE, 'Y', 'N', 'yes', or 'no'." = length(x) == 1 &&
      !is.null(x) &&
      !is.na(x)
  )

  if (is.character(x)) {
    x <- tolower(x)

    if (x %in% c("yes", "y")) {
      x <- TRUE
    } else if (x %in% c("no", "n")) {
      x <- FALSE
    } else {
      stop("x must be one of TRUE, FALSE, 'Y', 'N', 'yes', or 'no'.")
    }
  }

  ifelse(isTRUE(x), "yes", "no")
}
