#' Format a vector of keyword names for inline `roxygen2` use
#'
#' Wraps each element in backticks (so `roxygen2` markdown renders each
#' key as `\code{}` in the generated `.Rd`, which also keeps these
#' identifiers out of `spelling::spell_check_package()`) and joins with
#' `, `. Intended for inline expansion via `` `r .fmtKeys(.someKeys)` ``
#' so users see the literal allowed values in the rendered manual rather
#' than a reference to a non-exported internal vector.
#'
#' @param x Character vector of keyword names.
#'
#' @return A single character string.
#'
#' @keywords internal
.fmtKeys <- function(x) {
  paste(sprintf("`%s`", x), collapse = ", ")
}

#' @keywords internal
.checkPath <- function(path) {
  path <- fs::path_norm(path) |> fs::dir_create()

  return(path)
}

#' @keywords internal
.relPath <- function(path, start = ".") {
  if (is.null(path)) {
    return(NULL)
  }
  vapply(
    path,
    function(p) if (is.na(p)) NA_character_ else fs::path_rel(p, start),
    character(1),
    USE.NAMES = FALSE
  )
}

#' @keywords internal
landisutilsVersion <- function() {
  packageVersion("landisutils")
}

#' @keywords internal
landisutilsHeader <- function() {
  c(
    glue::glue(">> generated by `landisutils` (v{landisutilsVersion()}) on {date()}"),
    glue::glue(">> do not edit by hand; manual changes to this file may be overwritten"),
    glue::glue("")
  )
}

#' Write a LANDIS-II `LandisData` header block
#'
#' Emits the `landisutils` auto-generated file header followed by the
#' `LandisData  "<x>"` line and a blank line. Every LANDIS-II input file
#' starts with this block.
#'
#' @param x Character. The `LandisData` value (extension or scenario name).
#'
#' @template return_insert
#'
#' @export
insertLandisData <- function(x) {
  c(landisutilsHeader(), glue::glue("LandisData  \"{x}\""), glue::glue(""))
}

#' Specify an input parameter value for an extension
#'
#' @param type Character, specifying the parameter type (i.e., the LANDIS-II name for the input).
#'
#' @param value A single parameter value of integer, numeric, or character type.
#'
#' @param blank_line Logical. Should a blank line be added after the line?
#'
#' @template return_insert
#'
#' @export
insertValue <- function(type, value, blank_line = TRUE) {
  stopifnot(length(value) == 1)

  if (!is.na(value)) {
    if (is.character(value)) {
      ## LANDIS-II's parser only accepts double-quoted strings when the value contains whitespace;
      ## bare tokens (yes/no, enum values, paths without spaces) must be emitted unquoted.
      if (grepl("[[:space:]]", value)) {
        out <- glue::glue("{type}    \"{value}\"")
      } else {
        out <- glue::glue("{type}    {value}")
      }
    } else {
      out <- glue::glue("{type}    {format(value, digits = 8, scientific = FALSE)}")
    }

    if (isTRUE(blank_line)) {
      out <- c(out, glue::glue(""))
    }
  } else {
    out <- ""
  }

  out
}

#' Specify an input file for an extension
#'
#' Emits a `<type>  <file>` line. `NULL` (and length-zero) input is treated
#' as "parameter omitted" and produces no output, matching how
#' [insertValue()] handles `NA`.
#'
#' @param type Character, specifying the parameter type (i.e., the LANDIS-II name for the input).
#'
#' @template param_file
#'
#' @template return_insert
#'
#' @export
insertFile <- function(type, file) {
  if (is.null(file) || length(file) == 0L) {
    return("")
  }

  insertValue(type, file)
}

#' Convert logical to a LANDIS-II yes/no or true/false token
#'
#' LANDIS-II input files mostly use the strings `"yes"` and `"no"` for
#' boolean parameters, but a few extensions (e.g. Magic Harvest's
#' `NoHarvestReInitialization`) require `"true"` / `"false"` instead.
#'
#' @param x one of `TRUE`, `FALSE`, `"Y"`, `"N"`, `"yes"`, `"no"`,
#'   `"T"`, `"F"`, `"true"`, `"false"` (case-insensitive).
#'
#' @return
#' - `yesno()`: character `"yes"` or `"no"`.
#' - `truefalse()`: character `"true"` or `"false"`.
#'
#' @export
#' @rdname yesno
yesno <- function(x) {
  stopifnot(
    "x must be one of TRUE, FALSE, 'Y', 'N', 'yes', or 'no'." = length(x) == 1 &&
      !is.null(x) &&
      !is.na(x)
  )

  if (is.character(x)) {
    x <- tolower(x)

    if (x %in% c("yes", "y", "true", "t")) {
      x <- TRUE
    } else if (x %in% c("no", "n", "false", "f")) {
      x <- FALSE
    } else {
      stop("x must be one of TRUE, FALSE, 'Y', 'N', 'yes', 'no', 'true', or 'false'.")
    }
  }

  ifelse(isTRUE(x), "yes", "no")
}

#' @export
#' @rdname yesno
truefalse <- function(x) {
  ifelse(yesno(x) == "yes", "true", "false")
}
